version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfiles/dev/Dockerfile
    volumes:
      - ./backend:/home/backend
    networks:
      - backend
      - frontend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfiles/dev/Dockerfile
    volumes:
      - ./frontend:/home/frontend
    networks:
      - frontend
    ports:
      - "3000:3000"
    tty: true

networks:
  backend:
  frontend:
