version: "3.8"

services:
  backend:
    networks:
      - backend
      - frontend
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfiles/dev/Dockerfile
    volumes:
      - ./frontend:/home/frontend
    networks:
      - frontend
    ports:
      - "3000:3000"
    tty: true

  db:
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always

networks:
  backend:
  frontend:
